---
- hosts: nginx
  become: yes
  gather_facts: no
  roles:
    - common
  tasks:
    - name: ensure packages are installed
      apt:
        name: nginx
    - name: Creates ads directory
      file:
        path: /var/www/ads.example.com/html/
        state: directory
    - name: Creates auth directory
      file:
        path: /var/www/auth.example.com/html/
        state: directory
    - name: ensure nginx config is uploaded
      copy:
        src: ads.nginx.conf
        dest: /etc/nginx/conf.d/ads.conf
      notify:
        - restart nginx
  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: reloaded
