---
- hosts: rabbitmq
  become: yes
  gather_facts: no
  tasks:
    - name: ensure trusted key from github.com is added
      apt_key:
        # 1. https://github.com/rabbitmq/signing-keys/releases
        # url: 'https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-launchpad-ppa-signing-key.asc'
        # 2. https://www.rabbitmq.com/install-debian.html#apt-launchpad-erlang
        url: 'https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc'
        state: present

    - name: ensure rabbitmq launchpad.net repository is added
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_repository_module.html
      ansible.builtin.apt_repository:
        # 1. https://averyuslaner.com/fixing-rabbitmq-sources-repository/
        # repo: 'deb http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu bionic main'
        # 2. https://www.rabbitmq.com/install-debian.html#apt-launchpad-erlang
        repo: 'deb http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu focal main'
        state: present

    - name: ensure trusted key from packagecloud.io or github.com is added
      apt_key:
        # 1. https://www.rabbitmq.com/install-debian.html#apt-quick-start-packagecloud
        url: 'https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey'
        state: present

    - name: ensure rabbitmq packagecloud.io or cloudsmith.io repository is added
      # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_repository_module.html
      ansible.builtin.apt_repository:
        # 1. https://www.rabbitmq.com/install-debian.html#apt-quick-start-packagecloud
        repo: 'deb https://packagecloud.io/rabbitmq/rabbitmq-server/ubuntu/ focal main'
        state: present

    - name: ensure package is installed
      apt:
        name: rabbitmq-server
    - name: ensure rabbitmq plugins are installed
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - restart rabbitmq
  handlers:
    - name: restart rabbitmq
      service:
        name: rabbitmq-server
        state: restarted
- hosts: rabbitmq
  become: yes
  gather_facts: no
  vars_files:
    - secrets.yml
  vars:
    user: ads
    password: '{{ rabbitmq_password }}'
  tasks:
    - name: ensure rabbitmq user is present
      rabbitmq_user:
        user: '{{ user }}'
        password: '{{ password }}'
        tags: 'administrator'
        vhost: /
        configure_priv: .*
        write_priv: .*
        read_priv: .*
        state: present
    - name: ensure guest user is absent
      rabbitmq_user:
        user: guest
        state: absent
