# https://www.elastic.co/guide/en/beats/filebeat/7.2/filebeat-input-docker.html
filebeat.inputs:
- type: docker
  containers.ids: '*'

# https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover.html
filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        # https://www.elastic.co/guide/en/beats/filebeat/current/defining-processors.html#conditions
        - condition.or:
            - contains.docker.container.name: ads
            - contains.docker.container.name: auth
            - contains.docker.container.name: geocoder
          config:
            - type: container
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              exclude_lines: ["^\\s+[\\-`('.|_]"] # drop asciiart lines

processors:
  # https://www.elastic.co/guide/en/beats/filebeat/current/add-docker-metadata.html
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"

  # https://www.elastic.co/guide/en/beats/filebeat/8.5/decode-json-fields.html
  - decode_json_fields:
      fields: ["message"]
      target: "json"
      overwrite_keys: true

logging.json: true
logging.metrics.enabled: false

output.logstash:
  hosts: "logstash:5044"
